In [1]:
import pandas as pd
import numpy as np

In [2]:
from tensorflow import keras

In [3]:
from keras.preprocessing.text import one_hot

In [6]:
# Sentence 
sent=['the glass od milk','the glass of juice',
      'the cup of tea','i m a good boy','i m a good developper',
      'understand the Remaining of words','your video are good']

In [7]:
sent

['the glass od milk',
 'the glass of juice',
 'the cup of tea',
 'i m a good boy',
 'i m a good developper',
 'understand the Remaining of words',
 'your video are good']

In [8]:
# Vocabulary Size
voc_size=10000

In [9]:
onehot_repr=[one_hot(word,voc_size) for word in sent]
print(onehot_repr)

[[7907, 6648, 367, 3153], [7907, 6648, 331, 435], [7907, 3536, 331, 7315], [4414, 7059, 4799, 6614, 665], [4414, 7059, 4799, 6614, 725], [1470, 7907, 4821, 331, 7418], [3433, 2009, 899, 6614]]


In [13]:
from keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
from tensorflow.keras.models import Sequential

In [15]:
sent_length=8
embeded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [16]:
print(embeded_docs)

[[   0    0    0    0 7907 6648  367 3153]
 [   0    0    0    0 7907 6648  331  435]
 [   0    0    0    0 7907 3536  331 7315]
 [   0    0    0 4414 7059 4799 6614  665]
 [   0    0    0 4414 7059 4799 6614  725]
 [   0    0    0 1470 7907 4821  331 7418]
 [   0    0    0    0 3433 2009  899 6614]]


In [18]:
# Select Feature means how many many u want to take 
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
print(model.predict(embeded_docs))

1/1 [==============================] - 0s 247ms/step
[[[-0.0207726   0.04183585 -0.03424006  0.03517261  0.02012144
   -0.04428111 -0.01789209 -0.01336709  0.00332674 -0.01452404]
  [-0.0207726   0.04183585 -0.03424006  0.03517261  0.02012144
   -0.04428111 -0.01789209 -0.01336709  0.00332674 -0.01452404]
  [-0.0207726   0.04183585 -0.03424006  0.03517261  0.02012144
   -0.04428111 -0.01789209 -0.01336709  0.00332674 -0.01452404]
  [-0.0207726   0.04183585 -0.03424006  0.03517261  0.02012144
   -0.04428111 -0.01789209 -0.01336709  0.00332674 -0.01452404]
  [-0.02533017  0.01903523  0.02821083  0.01177694  0.0091855
   -0.03663973  0.03504616 -0.0228394   0.02773816 -0.03101306]
  [-0.04027473  0.01248022  0.03186882 -0.00712711  0.01017808
    0.04535509  0.02568412 -0.00506363  0.03890568 -0.0372416 ]
  [-0.00928487 -0.04280094  0.01049634 -0.00751636 -0.03320724
   -0.00676229  0.04039807 -0.03190487  0.04247971  0.03891668]
  [ 0.03445842 -0.02348965  0.00885577 -0.04541384  0.02475

In [23]:
embeded_docs[0]

array([   0,    0,    0,    0, 7907, 6648,  367, 3153])

In [24]:
model.predict(embeded_docs[0])

1/1 [==============================] - 0s 98ms/step


array([[-0.0207726 ,  0.04183585, -0.03424006,  0.03517261,  0.02012144,
        -0.04428111, -0.01789209, -0.01336709,  0.00332674, -0.01452404],
       [-0.0207726 ,  0.04183585, -0.03424006,  0.03517261,  0.02012144,
        -0.04428111, -0.01789209, -0.01336709,  0.00332674, -0.01452404],
       [-0.0207726 ,  0.04183585, -0.03424006,  0.03517261,  0.02012144,
        -0.04428111, -0.01789209, -0.01336709,  0.00332674, -0.01452404],
       [-0.0207726 ,  0.04183585, -0.03424006,  0.03517261,  0.02012144,
        -0.04428111, -0.01789209, -0.01336709,  0.00332674, -0.01452404],
       [-0.02533017,  0.01903523,  0.02821083,  0.01177694,  0.0091855 ,
        -0.03663973,  0.03504616, -0.0228394 ,  0.02773816, -0.03101306],
       [-0.04027473,  0.01248022,  0.03186882, -0.00712711,  0.01017808,
         0.04535509,  0.02568412, -0.00506363,  0.03890568, -0.0372416 ],
       [-0.00928487, -0.04280094,  0.01049634, -0.00751636, -0.03320724,
        -0.00676229,  0.04039807, -0.03190487